version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booksproject

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - DB_URL=postgresql://postgres:password@db:5432/booksproject
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend